apiVersion: v1
kind: Pod
metadata:
  name: mixer
  namespace: istio-system
  labels:
    app: istio-mixer
    istio: mixer
    chart: mixer-1.1.0
    release: istio
    version: 1.1.0
    heritage: Tiller
  annotations:
    sidecar.istio.io/inject: "false"
    scheduler.alpha.kubernetes.io/critical-pod: ""
spec:
  serviceAccountName: istio-mixer-service-account
  volumes:
  - name: istio-certs
    secret:
      secretName: istio.istio-mixer-service-account
      optional: true
  - name: uds-socket
    emptyDir: {}
  affinity:      
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 2
        preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
      - weight: 2
        preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - ppc64le
      - weight: 2
        preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - s390x
  containers:
  - name: mixer
    image: gcr.io/bpy-istio/mixer:head
    imagePullPolicy: Always
    ports:
    - containerPort: 9093
    - containerPort: 42422
    args:
      - --configStoreURL=k8s://
      - --configDefaultNamespace=istio-system
      - --trace_zipkin_url=http://zipkin:9411/api/v1/spans
      - --numCheckCacheEntries=0
      - --maxConcurrentStreams=10000
      - --apiWorkerPoolSize=10000
    volumeMounts:
    - name: uds-socket
      mountPath: /sock
    livenessProbe:
      httpGet:
        path: /version
        port: 9093
      initialDelaySeconds: 5
      periodSeconds: 5
