---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prom-example
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: prom-example
        image: gcr.io/bpy-istio/prom-example:test
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prom-example
  labels:
    app: prom-example
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: prom-example
