// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template_handler_service.proto

#ifndef PROTOBUF_INCLUDED_template_5fhandler_5fservice_2eproto
#define PROTOBUF_INCLUDED_template_5fhandler_5fservice_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "gogoproto/gogo.pb.h"
#include "mixer/adapter/model/v1beta1/extensions.pb.h"
#include <google/protobuf/any.pb.h>
#include "mixer/adapter/model/v1beta1/report.pb.h"
#include "policy/v1beta1/value_type.pb.h"
#include "policy/v1beta1/type.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_template_5fhandler_5fservice_2eproto 

namespace protobuf_template_5fhandler_5fservice_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[10];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_template_5fhandler_5fservice_2eproto
namespace metric {
class HandleMetricRequest;
class HandleMetricRequestDefaultTypeInternal;
extern HandleMetricRequestDefaultTypeInternal _HandleMetricRequest_default_instance_;
class InstanceMsg;
class InstanceMsgDefaultTypeInternal;
extern InstanceMsgDefaultTypeInternal _InstanceMsg_default_instance_;
class InstanceMsg_DimensionsEntry_DoNotUse;
class InstanceMsg_DimensionsEntry_DoNotUseDefaultTypeInternal;
extern InstanceMsg_DimensionsEntry_DoNotUseDefaultTypeInternal _InstanceMsg_DimensionsEntry_DoNotUse_default_instance_;
class InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse;
class InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUseDefaultTypeInternal;
extern InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUseDefaultTypeInternal _InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse_default_instance_;
class InstanceParam;
class InstanceParamDefaultTypeInternal;
extern InstanceParamDefaultTypeInternal _InstanceParam_default_instance_;
class InstanceParam_DimensionsEntry_DoNotUse;
class InstanceParam_DimensionsEntry_DoNotUseDefaultTypeInternal;
extern InstanceParam_DimensionsEntry_DoNotUseDefaultTypeInternal _InstanceParam_DimensionsEntry_DoNotUse_default_instance_;
class InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse;
class InstanceParam_MonitoredResourceDimensionsEntry_DoNotUseDefaultTypeInternal;
extern InstanceParam_MonitoredResourceDimensionsEntry_DoNotUseDefaultTypeInternal _InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse_default_instance_;
class Type;
class TypeDefaultTypeInternal;
extern TypeDefaultTypeInternal _Type_default_instance_;
class Type_DimensionsEntry_DoNotUse;
class Type_DimensionsEntry_DoNotUseDefaultTypeInternal;
extern Type_DimensionsEntry_DoNotUseDefaultTypeInternal _Type_DimensionsEntry_DoNotUse_default_instance_;
class Type_MonitoredResourceDimensionsEntry_DoNotUse;
class Type_MonitoredResourceDimensionsEntry_DoNotUseDefaultTypeInternal;
extern Type_MonitoredResourceDimensionsEntry_DoNotUseDefaultTypeInternal _Type_MonitoredResourceDimensionsEntry_DoNotUse_default_instance_;
}  // namespace metric
namespace google {
namespace protobuf {
template<> ::metric::HandleMetricRequest* Arena::CreateMaybeMessage<::metric::HandleMetricRequest>(Arena*);
template<> ::metric::InstanceMsg* Arena::CreateMaybeMessage<::metric::InstanceMsg>(Arena*);
template<> ::metric::InstanceMsg_DimensionsEntry_DoNotUse* Arena::CreateMaybeMessage<::metric::InstanceMsg_DimensionsEntry_DoNotUse>(Arena*);
template<> ::metric::InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse* Arena::CreateMaybeMessage<::metric::InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse>(Arena*);
template<> ::metric::InstanceParam* Arena::CreateMaybeMessage<::metric::InstanceParam>(Arena*);
template<> ::metric::InstanceParam_DimensionsEntry_DoNotUse* Arena::CreateMaybeMessage<::metric::InstanceParam_DimensionsEntry_DoNotUse>(Arena*);
template<> ::metric::InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse* Arena::CreateMaybeMessage<::metric::InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse>(Arena*);
template<> ::metric::Type* Arena::CreateMaybeMessage<::metric::Type>(Arena*);
template<> ::metric::Type_DimensionsEntry_DoNotUse* Arena::CreateMaybeMessage<::metric::Type_DimensionsEntry_DoNotUse>(Arena*);
template<> ::metric::Type_MonitoredResourceDimensionsEntry_DoNotUse* Arena::CreateMaybeMessage<::metric::Type_MonitoredResourceDimensionsEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace metric {

// ===================================================================

class HandleMetricRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metric.HandleMetricRequest) */ {
 public:
  HandleMetricRequest();
  virtual ~HandleMetricRequest();

  HandleMetricRequest(const HandleMetricRequest& from);

  inline HandleMetricRequest& operator=(const HandleMetricRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HandleMetricRequest(HandleMetricRequest&& from) noexcept
    : HandleMetricRequest() {
    *this = ::std::move(from);
  }

  inline HandleMetricRequest& operator=(HandleMetricRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HandleMetricRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HandleMetricRequest* internal_default_instance() {
    return reinterpret_cast<const HandleMetricRequest*>(
               &_HandleMetricRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(HandleMetricRequest* other);
  friend void swap(HandleMetricRequest& a, HandleMetricRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HandleMetricRequest* New() const final {
    return CreateMaybeMessage<HandleMetricRequest>(NULL);
  }

  HandleMetricRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HandleMetricRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HandleMetricRequest& from);
  void MergeFrom(const HandleMetricRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HandleMetricRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .metric.InstanceMsg instances = 1;
  int instances_size() const;
  void clear_instances();
  static const int kInstancesFieldNumber = 1;
  ::metric::InstanceMsg* mutable_instances(int index);
  ::google::protobuf::RepeatedPtrField< ::metric::InstanceMsg >*
      mutable_instances();
  const ::metric::InstanceMsg& instances(int index) const;
  ::metric::InstanceMsg* add_instances();
  const ::google::protobuf::RepeatedPtrField< ::metric::InstanceMsg >&
      instances() const;

  // string dedup_id = 3;
  void clear_dedup_id();
  static const int kDedupIdFieldNumber = 3;
  const ::std::string& dedup_id() const;
  void set_dedup_id(const ::std::string& value);
  #if LANG_CXX11
  void set_dedup_id(::std::string&& value);
  #endif
  void set_dedup_id(const char* value);
  void set_dedup_id(const char* value, size_t size);
  ::std::string* mutable_dedup_id();
  ::std::string* release_dedup_id();
  void set_allocated_dedup_id(::std::string* dedup_id);

  // .google.protobuf.Any adapter_config = 2;
  bool has_adapter_config() const;
  void clear_adapter_config();
  static const int kAdapterConfigFieldNumber = 2;
  private:
  const ::google::protobuf::Any& _internal_adapter_config() const;
  public:
  const ::google::protobuf::Any& adapter_config() const;
  ::google::protobuf::Any* release_adapter_config();
  ::google::protobuf::Any* mutable_adapter_config();
  void set_allocated_adapter_config(::google::protobuf::Any* adapter_config);

  // @@protoc_insertion_point(class_scope:metric.HandleMetricRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::metric::InstanceMsg > instances_;
  ::google::protobuf::internal::ArenaStringPtr dedup_id_;
  ::google::protobuf::Any* adapter_config_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_template_5fhandler_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InstanceMsg_DimensionsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<InstanceMsg_DimensionsEntry_DoNotUse, 
    ::std::string, ::istio::policy::v1beta1::Value,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<InstanceMsg_DimensionsEntry_DoNotUse, 
    ::std::string, ::istio::policy::v1beta1::Value,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  InstanceMsg_DimensionsEntry_DoNotUse();
  InstanceMsg_DimensionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const InstanceMsg_DimensionsEntry_DoNotUse& other);
  static const InstanceMsg_DimensionsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const InstanceMsg_DimensionsEntry_DoNotUse*>(&_InstanceMsg_DimensionsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse, 
    ::std::string, ::istio::policy::v1beta1::Value,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse, 
    ::std::string, ::istio::policy::v1beta1::Value,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse();
  InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse& other);
  static const InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse*>(&_InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class InstanceMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metric.InstanceMsg) */ {
 public:
  InstanceMsg();
  virtual ~InstanceMsg();

  InstanceMsg(const InstanceMsg& from);

  inline InstanceMsg& operator=(const InstanceMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InstanceMsg(InstanceMsg&& from) noexcept
    : InstanceMsg() {
    *this = ::std::move(from);
  }

  inline InstanceMsg& operator=(InstanceMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InstanceMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InstanceMsg* internal_default_instance() {
    return reinterpret_cast<const InstanceMsg*>(
               &_InstanceMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(InstanceMsg* other);
  friend void swap(InstanceMsg& a, InstanceMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InstanceMsg* New() const final {
    return CreateMaybeMessage<InstanceMsg>(NULL);
  }

  InstanceMsg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InstanceMsg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InstanceMsg& from);
  void MergeFrom(const InstanceMsg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstanceMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .istio.policy.v1beta1.Value> dimensions = 2;
  int dimensions_size() const;
  void clear_dimensions();
  static const int kDimensionsFieldNumber = 2;
  const ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::Value >&
      dimensions() const;
  ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::Value >*
      mutable_dimensions();

  // map<string, .istio.policy.v1beta1.Value> monitored_resource_dimensions = 4;
  int monitored_resource_dimensions_size() const;
  void clear_monitored_resource_dimensions();
  static const int kMonitoredResourceDimensionsFieldNumber = 4;
  const ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::Value >&
      monitored_resource_dimensions() const;
  ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::Value >*
      mutable_monitored_resource_dimensions();

  // string monitored_resource_type = 3;
  void clear_monitored_resource_type();
  static const int kMonitoredResourceTypeFieldNumber = 3;
  const ::std::string& monitored_resource_type() const;
  void set_monitored_resource_type(const ::std::string& value);
  #if LANG_CXX11
  void set_monitored_resource_type(::std::string&& value);
  #endif
  void set_monitored_resource_type(const char* value);
  void set_monitored_resource_type(const char* value, size_t size);
  ::std::string* mutable_monitored_resource_type();
  ::std::string* release_monitored_resource_type();
  void set_allocated_monitored_resource_type(::std::string* monitored_resource_type);

  // string name = 72295727;
  void clear_name();
  static const int kNameFieldNumber = 72295727;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // .istio.policy.v1beta1.Value value = 1;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 1;
  private:
  const ::istio::policy::v1beta1::Value& _internal_value() const;
  public:
  const ::istio::policy::v1beta1::Value& value() const;
  ::istio::policy::v1beta1::Value* release_value();
  ::istio::policy::v1beta1::Value* mutable_value();
  void set_allocated_value(::istio::policy::v1beta1::Value* value);

  // @@protoc_insertion_point(class_scope:metric.InstanceMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      InstanceMsg_DimensionsEntry_DoNotUse,
      ::std::string, ::istio::policy::v1beta1::Value,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > dimensions_;
  ::google::protobuf::internal::MapField<
      InstanceMsg_MonitoredResourceDimensionsEntry_DoNotUse,
      ::std::string, ::istio::policy::v1beta1::Value,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > monitored_resource_dimensions_;
  ::google::protobuf::internal::ArenaStringPtr monitored_resource_type_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::istio::policy::v1beta1::Value* value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_template_5fhandler_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Type_DimensionsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Type_DimensionsEntry_DoNotUse, 
    ::std::string, ::istio::policy::v1beta1::ValueType,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<Type_DimensionsEntry_DoNotUse, 
    ::std::string, ::istio::policy::v1beta1::ValueType,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
    0 > SuperType;
  Type_DimensionsEntry_DoNotUse();
  Type_DimensionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Type_DimensionsEntry_DoNotUse& other);
  static const Type_DimensionsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Type_DimensionsEntry_DoNotUse*>(&_Type_DimensionsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Type_MonitoredResourceDimensionsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<Type_MonitoredResourceDimensionsEntry_DoNotUse, 
    ::std::string, ::istio::policy::v1beta1::ValueType,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<Type_MonitoredResourceDimensionsEntry_DoNotUse, 
    ::std::string, ::istio::policy::v1beta1::ValueType,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
    0 > SuperType;
  Type_MonitoredResourceDimensionsEntry_DoNotUse();
  Type_MonitoredResourceDimensionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const Type_MonitoredResourceDimensionsEntry_DoNotUse& other);
  static const Type_MonitoredResourceDimensionsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Type_MonitoredResourceDimensionsEntry_DoNotUse*>(&_Type_MonitoredResourceDimensionsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class Type : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metric.Type) */ {
 public:
  Type();
  virtual ~Type();

  Type(const Type& from);

  inline Type& operator=(const Type& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Type(Type&& from) noexcept
    : Type() {
    *this = ::std::move(from);
  }

  inline Type& operator=(Type&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Type& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Type* internal_default_instance() {
    return reinterpret_cast<const Type*>(
               &_Type_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(Type* other);
  friend void swap(Type& a, Type& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Type* New() const final {
    return CreateMaybeMessage<Type>(NULL);
  }

  Type* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Type>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Type& from);
  void MergeFrom(const Type& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Type* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .istio.policy.v1beta1.ValueType> dimensions = 2;
  int dimensions_size() const;
  void clear_dimensions();
  static const int kDimensionsFieldNumber = 2;
  const ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::ValueType >&
      dimensions() const;
  ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::ValueType >*
      mutable_dimensions();

  // map<string, .istio.policy.v1beta1.ValueType> monitored_resource_dimensions = 4;
  int monitored_resource_dimensions_size() const;
  void clear_monitored_resource_dimensions();
  static const int kMonitoredResourceDimensionsFieldNumber = 4;
  const ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::ValueType >&
      monitored_resource_dimensions() const;
  ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::ValueType >*
      mutable_monitored_resource_dimensions();

  // .istio.policy.v1beta1.ValueType value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::istio::policy::v1beta1::ValueType value() const;
  void set_value(::istio::policy::v1beta1::ValueType value);

  // @@protoc_insertion_point(class_scope:metric.Type)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      Type_DimensionsEntry_DoNotUse,
      ::std::string, ::istio::policy::v1beta1::ValueType,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > dimensions_;
  ::google::protobuf::internal::MapField<
      Type_MonitoredResourceDimensionsEntry_DoNotUse,
      ::std::string, ::istio::policy::v1beta1::ValueType,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > monitored_resource_dimensions_;
  int value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_template_5fhandler_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InstanceParam_DimensionsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<InstanceParam_DimensionsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<InstanceParam_DimensionsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  InstanceParam_DimensionsEntry_DoNotUse();
  InstanceParam_DimensionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const InstanceParam_DimensionsEntry_DoNotUse& other);
  static const InstanceParam_DimensionsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const InstanceParam_DimensionsEntry_DoNotUse*>(&_InstanceParam_DimensionsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse, 
    ::std::string, ::std::string,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse();
  InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse& other);
  static const InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse*>(&_InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class InstanceParam : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:metric.InstanceParam) */ {
 public:
  InstanceParam();
  virtual ~InstanceParam();

  InstanceParam(const InstanceParam& from);

  inline InstanceParam& operator=(const InstanceParam& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InstanceParam(InstanceParam&& from) noexcept
    : InstanceParam() {
    *this = ::std::move(from);
  }

  inline InstanceParam& operator=(InstanceParam&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InstanceParam& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InstanceParam* internal_default_instance() {
    return reinterpret_cast<const InstanceParam*>(
               &_InstanceParam_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(InstanceParam* other);
  friend void swap(InstanceParam& a, InstanceParam& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InstanceParam* New() const final {
    return CreateMaybeMessage<InstanceParam>(NULL);
  }

  InstanceParam* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InstanceParam>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InstanceParam& from);
  void MergeFrom(const InstanceParam& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstanceParam* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> dimensions = 2;
  int dimensions_size() const;
  void clear_dimensions();
  static const int kDimensionsFieldNumber = 2;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      dimensions() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_dimensions();

  // map<string, string> monitored_resource_dimensions = 4;
  int monitored_resource_dimensions_size() const;
  void clear_monitored_resource_dimensions();
  static const int kMonitoredResourceDimensionsFieldNumber = 4;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      monitored_resource_dimensions() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_monitored_resource_dimensions();

  // string value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // string monitored_resource_type = 3;
  void clear_monitored_resource_type();
  static const int kMonitoredResourceTypeFieldNumber = 3;
  const ::std::string& monitored_resource_type() const;
  void set_monitored_resource_type(const ::std::string& value);
  #if LANG_CXX11
  void set_monitored_resource_type(::std::string&& value);
  #endif
  void set_monitored_resource_type(const char* value);
  void set_monitored_resource_type(const char* value, size_t size);
  ::std::string* mutable_monitored_resource_type();
  ::std::string* release_monitored_resource_type();
  void set_allocated_monitored_resource_type(::std::string* monitored_resource_type);

  // @@protoc_insertion_point(class_scope:metric.InstanceParam)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      InstanceParam_DimensionsEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > dimensions_;
  ::google::protobuf::internal::MapField<
      InstanceParam_MonitoredResourceDimensionsEntry_DoNotUse,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > monitored_resource_dimensions_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::internal::ArenaStringPtr monitored_resource_type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_template_5fhandler_5fservice_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HandleMetricRequest

// repeated .metric.InstanceMsg instances = 1;
inline int HandleMetricRequest::instances_size() const {
  return instances_.size();
}
inline void HandleMetricRequest::clear_instances() {
  instances_.Clear();
}
inline ::metric::InstanceMsg* HandleMetricRequest::mutable_instances(int index) {
  // @@protoc_insertion_point(field_mutable:metric.HandleMetricRequest.instances)
  return instances_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::metric::InstanceMsg >*
HandleMetricRequest::mutable_instances() {
  // @@protoc_insertion_point(field_mutable_list:metric.HandleMetricRequest.instances)
  return &instances_;
}
inline const ::metric::InstanceMsg& HandleMetricRequest::instances(int index) const {
  // @@protoc_insertion_point(field_get:metric.HandleMetricRequest.instances)
  return instances_.Get(index);
}
inline ::metric::InstanceMsg* HandleMetricRequest::add_instances() {
  // @@protoc_insertion_point(field_add:metric.HandleMetricRequest.instances)
  return instances_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::metric::InstanceMsg >&
HandleMetricRequest::instances() const {
  // @@protoc_insertion_point(field_list:metric.HandleMetricRequest.instances)
  return instances_;
}

// .google.protobuf.Any adapter_config = 2;
inline bool HandleMetricRequest::has_adapter_config() const {
  return this != internal_default_instance() && adapter_config_ != NULL;
}
inline const ::google::protobuf::Any& HandleMetricRequest::_internal_adapter_config() const {
  return *adapter_config_;
}
inline const ::google::protobuf::Any& HandleMetricRequest::adapter_config() const {
  const ::google::protobuf::Any* p = adapter_config_;
  // @@protoc_insertion_point(field_get:metric.HandleMetricRequest.adapter_config)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Any*>(
      &::google::protobuf::_Any_default_instance_);
}
inline ::google::protobuf::Any* HandleMetricRequest::release_adapter_config() {
  // @@protoc_insertion_point(field_release:metric.HandleMetricRequest.adapter_config)
  
  ::google::protobuf::Any* temp = adapter_config_;
  adapter_config_ = NULL;
  return temp;
}
inline ::google::protobuf::Any* HandleMetricRequest::mutable_adapter_config() {
  
  if (adapter_config_ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::Any>(GetArenaNoVirtual());
    adapter_config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:metric.HandleMetricRequest.adapter_config)
  return adapter_config_;
}
inline void HandleMetricRequest::set_allocated_adapter_config(::google::protobuf::Any* adapter_config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(adapter_config_);
  }
  if (adapter_config) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      adapter_config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, adapter_config, submessage_arena);
    }
    
  } else {
    
  }
  adapter_config_ = adapter_config;
  // @@protoc_insertion_point(field_set_allocated:metric.HandleMetricRequest.adapter_config)
}

// string dedup_id = 3;
inline void HandleMetricRequest::clear_dedup_id() {
  dedup_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HandleMetricRequest::dedup_id() const {
  // @@protoc_insertion_point(field_get:metric.HandleMetricRequest.dedup_id)
  return dedup_id_.GetNoArena();
}
inline void HandleMetricRequest::set_dedup_id(const ::std::string& value) {
  
  dedup_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metric.HandleMetricRequest.dedup_id)
}
#if LANG_CXX11
inline void HandleMetricRequest::set_dedup_id(::std::string&& value) {
  
  dedup_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metric.HandleMetricRequest.dedup_id)
}
#endif
inline void HandleMetricRequest::set_dedup_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  dedup_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metric.HandleMetricRequest.dedup_id)
}
inline void HandleMetricRequest::set_dedup_id(const char* value, size_t size) {
  
  dedup_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metric.HandleMetricRequest.dedup_id)
}
inline ::std::string* HandleMetricRequest::mutable_dedup_id() {
  
  // @@protoc_insertion_point(field_mutable:metric.HandleMetricRequest.dedup_id)
  return dedup_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HandleMetricRequest::release_dedup_id() {
  // @@protoc_insertion_point(field_release:metric.HandleMetricRequest.dedup_id)
  
  return dedup_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HandleMetricRequest::set_allocated_dedup_id(::std::string* dedup_id) {
  if (dedup_id != NULL) {
    
  } else {
    
  }
  dedup_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dedup_id);
  // @@protoc_insertion_point(field_set_allocated:metric.HandleMetricRequest.dedup_id)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// InstanceMsg

// string name = 72295727;
inline void InstanceMsg::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& InstanceMsg::name() const {
  // @@protoc_insertion_point(field_get:metric.InstanceMsg.name)
  return name_.GetNoArena();
}
inline void InstanceMsg::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metric.InstanceMsg.name)
}
#if LANG_CXX11
inline void InstanceMsg::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metric.InstanceMsg.name)
}
#endif
inline void InstanceMsg::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metric.InstanceMsg.name)
}
inline void InstanceMsg::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metric.InstanceMsg.name)
}
inline ::std::string* InstanceMsg::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:metric.InstanceMsg.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InstanceMsg::release_name() {
  // @@protoc_insertion_point(field_release:metric.InstanceMsg.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InstanceMsg::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:metric.InstanceMsg.name)
}

// .istio.policy.v1beta1.Value value = 1;
inline bool InstanceMsg::has_value() const {
  return this != internal_default_instance() && value_ != NULL;
}
inline const ::istio::policy::v1beta1::Value& InstanceMsg::_internal_value() const {
  return *value_;
}
inline const ::istio::policy::v1beta1::Value& InstanceMsg::value() const {
  const ::istio::policy::v1beta1::Value* p = value_;
  // @@protoc_insertion_point(field_get:metric.InstanceMsg.value)
  return p != NULL ? *p : *reinterpret_cast<const ::istio::policy::v1beta1::Value*>(
      &::istio::policy::v1beta1::_Value_default_instance_);
}
inline ::istio::policy::v1beta1::Value* InstanceMsg::release_value() {
  // @@protoc_insertion_point(field_release:metric.InstanceMsg.value)
  
  ::istio::policy::v1beta1::Value* temp = value_;
  value_ = NULL;
  return temp;
}
inline ::istio::policy::v1beta1::Value* InstanceMsg::mutable_value() {
  
  if (value_ == NULL) {
    auto* p = CreateMaybeMessage<::istio::policy::v1beta1::Value>(GetArenaNoVirtual());
    value_ = p;
  }
  // @@protoc_insertion_point(field_mutable:metric.InstanceMsg.value)
  return value_;
}
inline void InstanceMsg::set_allocated_value(::istio::policy::v1beta1::Value* value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(value_);
  }
  if (value) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, value, submessage_arena);
    }
    
  } else {
    
  }
  value_ = value;
  // @@protoc_insertion_point(field_set_allocated:metric.InstanceMsg.value)
}

// map<string, .istio.policy.v1beta1.Value> dimensions = 2;
inline int InstanceMsg::dimensions_size() const {
  return dimensions_.size();
}
inline const ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::Value >&
InstanceMsg::dimensions() const {
  // @@protoc_insertion_point(field_map:metric.InstanceMsg.dimensions)
  return dimensions_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::Value >*
InstanceMsg::mutable_dimensions() {
  // @@protoc_insertion_point(field_mutable_map:metric.InstanceMsg.dimensions)
  return dimensions_.MutableMap();
}

// string monitored_resource_type = 3;
inline void InstanceMsg::clear_monitored_resource_type() {
  monitored_resource_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& InstanceMsg::monitored_resource_type() const {
  // @@protoc_insertion_point(field_get:metric.InstanceMsg.monitored_resource_type)
  return monitored_resource_type_.GetNoArena();
}
inline void InstanceMsg::set_monitored_resource_type(const ::std::string& value) {
  
  monitored_resource_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metric.InstanceMsg.monitored_resource_type)
}
#if LANG_CXX11
inline void InstanceMsg::set_monitored_resource_type(::std::string&& value) {
  
  monitored_resource_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metric.InstanceMsg.monitored_resource_type)
}
#endif
inline void InstanceMsg::set_monitored_resource_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  monitored_resource_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metric.InstanceMsg.monitored_resource_type)
}
inline void InstanceMsg::set_monitored_resource_type(const char* value, size_t size) {
  
  monitored_resource_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metric.InstanceMsg.monitored_resource_type)
}
inline ::std::string* InstanceMsg::mutable_monitored_resource_type() {
  
  // @@protoc_insertion_point(field_mutable:metric.InstanceMsg.monitored_resource_type)
  return monitored_resource_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InstanceMsg::release_monitored_resource_type() {
  // @@protoc_insertion_point(field_release:metric.InstanceMsg.monitored_resource_type)
  
  return monitored_resource_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InstanceMsg::set_allocated_monitored_resource_type(::std::string* monitored_resource_type) {
  if (monitored_resource_type != NULL) {
    
  } else {
    
  }
  monitored_resource_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), monitored_resource_type);
  // @@protoc_insertion_point(field_set_allocated:metric.InstanceMsg.monitored_resource_type)
}

// map<string, .istio.policy.v1beta1.Value> monitored_resource_dimensions = 4;
inline int InstanceMsg::monitored_resource_dimensions_size() const {
  return monitored_resource_dimensions_.size();
}
inline const ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::Value >&
InstanceMsg::monitored_resource_dimensions() const {
  // @@protoc_insertion_point(field_map:metric.InstanceMsg.monitored_resource_dimensions)
  return monitored_resource_dimensions_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::Value >*
InstanceMsg::mutable_monitored_resource_dimensions() {
  // @@protoc_insertion_point(field_mutable_map:metric.InstanceMsg.monitored_resource_dimensions)
  return monitored_resource_dimensions_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Type

// .istio.policy.v1beta1.ValueType value = 1;
inline void Type::clear_value() {
  value_ = 0;
}
inline ::istio::policy::v1beta1::ValueType Type::value() const {
  // @@protoc_insertion_point(field_get:metric.Type.value)
  return static_cast< ::istio::policy::v1beta1::ValueType >(value_);
}
inline void Type::set_value(::istio::policy::v1beta1::ValueType value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:metric.Type.value)
}

// map<string, .istio.policy.v1beta1.ValueType> dimensions = 2;
inline int Type::dimensions_size() const {
  return dimensions_.size();
}
inline void Type::clear_dimensions() {
  dimensions_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::ValueType >&
Type::dimensions() const {
  // @@protoc_insertion_point(field_map:metric.Type.dimensions)
  return dimensions_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::ValueType >*
Type::mutable_dimensions() {
  // @@protoc_insertion_point(field_mutable_map:metric.Type.dimensions)
  return dimensions_.MutableMap();
}

// map<string, .istio.policy.v1beta1.ValueType> monitored_resource_dimensions = 4;
inline int Type::monitored_resource_dimensions_size() const {
  return monitored_resource_dimensions_.size();
}
inline void Type::clear_monitored_resource_dimensions() {
  monitored_resource_dimensions_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::ValueType >&
Type::monitored_resource_dimensions() const {
  // @@protoc_insertion_point(field_map:metric.Type.monitored_resource_dimensions)
  return monitored_resource_dimensions_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::istio::policy::v1beta1::ValueType >*
Type::mutable_monitored_resource_dimensions() {
  // @@protoc_insertion_point(field_mutable_map:metric.Type.monitored_resource_dimensions)
  return monitored_resource_dimensions_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// InstanceParam

// string value = 1;
inline void InstanceParam::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& InstanceParam::value() const {
  // @@protoc_insertion_point(field_get:metric.InstanceParam.value)
  return value_.GetNoArena();
}
inline void InstanceParam::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metric.InstanceParam.value)
}
#if LANG_CXX11
inline void InstanceParam::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metric.InstanceParam.value)
}
#endif
inline void InstanceParam::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metric.InstanceParam.value)
}
inline void InstanceParam::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metric.InstanceParam.value)
}
inline ::std::string* InstanceParam::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:metric.InstanceParam.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InstanceParam::release_value() {
  // @@protoc_insertion_point(field_release:metric.InstanceParam.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InstanceParam::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:metric.InstanceParam.value)
}

// map<string, string> dimensions = 2;
inline int InstanceParam::dimensions_size() const {
  return dimensions_.size();
}
inline void InstanceParam::clear_dimensions() {
  dimensions_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
InstanceParam::dimensions() const {
  // @@protoc_insertion_point(field_map:metric.InstanceParam.dimensions)
  return dimensions_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
InstanceParam::mutable_dimensions() {
  // @@protoc_insertion_point(field_mutable_map:metric.InstanceParam.dimensions)
  return dimensions_.MutableMap();
}

// string monitored_resource_type = 3;
inline void InstanceParam::clear_monitored_resource_type() {
  monitored_resource_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& InstanceParam::monitored_resource_type() const {
  // @@protoc_insertion_point(field_get:metric.InstanceParam.monitored_resource_type)
  return monitored_resource_type_.GetNoArena();
}
inline void InstanceParam::set_monitored_resource_type(const ::std::string& value) {
  
  monitored_resource_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:metric.InstanceParam.monitored_resource_type)
}
#if LANG_CXX11
inline void InstanceParam::set_monitored_resource_type(::std::string&& value) {
  
  monitored_resource_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:metric.InstanceParam.monitored_resource_type)
}
#endif
inline void InstanceParam::set_monitored_resource_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  monitored_resource_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:metric.InstanceParam.monitored_resource_type)
}
inline void InstanceParam::set_monitored_resource_type(const char* value, size_t size) {
  
  monitored_resource_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:metric.InstanceParam.monitored_resource_type)
}
inline ::std::string* InstanceParam::mutable_monitored_resource_type() {
  
  // @@protoc_insertion_point(field_mutable:metric.InstanceParam.monitored_resource_type)
  return monitored_resource_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InstanceParam::release_monitored_resource_type() {
  // @@protoc_insertion_point(field_release:metric.InstanceParam.monitored_resource_type)
  
  return monitored_resource_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InstanceParam::set_allocated_monitored_resource_type(::std::string* monitored_resource_type) {
  if (monitored_resource_type != NULL) {
    
  } else {
    
  }
  monitored_resource_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), monitored_resource_type);
  // @@protoc_insertion_point(field_set_allocated:metric.InstanceParam.monitored_resource_type)
}

// map<string, string> monitored_resource_dimensions = 4;
inline int InstanceParam::monitored_resource_dimensions_size() const {
  return monitored_resource_dimensions_.size();
}
inline void InstanceParam::clear_monitored_resource_dimensions() {
  monitored_resource_dimensions_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
InstanceParam::monitored_resource_dimensions() const {
  // @@protoc_insertion_point(field_map:metric.InstanceParam.monitored_resource_dimensions)
  return monitored_resource_dimensions_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
InstanceParam::mutable_monitored_resource_dimensions() {
  // @@protoc_insertion_point(field_mutable_map:metric.InstanceParam.monitored_resource_dimensions)
  return monitored_resource_dimensions_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace metric

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_template_5fhandler_5fservice_2eproto
