// Copyright 2018 Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED.

package server

import (
	"bytes"
	"context"
	"fmt"
	"net"
	"sync"

	proto "github.com/gogo/protobuf/types"
	"google.golang.org/grpc"
	adptModel "istio.io/api/mixer/adapter/model/v1beta1"
	"istio.io/api/policy/v1beta1"
	servicecontrol "istio.io/istio/mixer/adapter/servicecontrol"
	config "istio.io/istio/mixer/adapter/servicecontrol/config"
	"istio.io/istio/mixer/adapter/servicecontrol/template/servicecontrolreport"
	"istio.io/istio/mixer/pkg/adapter"
	"istio.io/istio/mixer/pkg/pool"
	"istio.io/istio/mixer/pkg/runtime/handler"
	"istio.io/istio/mixer/template/apikey"
	"istio.io/istio/mixer/template/quota"
)

type (
	// Server is basic server interface
	Server interface {
		Addr() string
		Close() error
		PromPort() int
		Run()
	}

	// NoSession models nosession adapter backend.
	NoSession struct {
		listener net.Listener
		shutdown chan error
		server   *grpc.Server

		rawcfg      []byte
		builder     adapter.HandlerBuilder
		env         adapter.Env
		builderLock sync.RWMutex

		apikeyHandler               apikey.Handler
		quotaHandler                quota.Handler
		servicecontrolreportHandler servicecontrolreport.Handler
	}
)

var _ apikey.HandleApiKeyServiceServer = &NoSession{}
var _ quota.HandleQuotaServiceServer = &NoSession{}
var _ servicecontrolreport.HandleServicecontrolReportServiceServer = &NoSession{}

func (s *NoSession) updateHandlers(rawcfg []byte) error {
	cfg := &config.Params{}

	if err := cfg.Unmarshal(rawcfg); err != nil {
		return err
	}

	s.builderLock.Lock()
	defer s.builderLock.Unlock()
	if 0 == bytes.Compare(rawcfg, s.rawcfg) {
		return nil
	}

	s.env.Logger().Infof("Loaded handler with: %v", cfg)
	s.builder.SetAdapterConfig(cfg)

	if ce := s.builder.Validate(); ce != nil {
		return ce
	}

	h, err := s.builder.Build(context.Background(), s.env)
	if err != nil {
		s.env.Logger().Errorf("could not build: %v", err)
		return err
	}
	s.rawcfg = rawcfg

	s.apikeyHandler = h.(apikey.Handler)
	s.quotaHandler = h.(quota.Handler)
	s.servicecontrolreportHandler = h.(servicecontrolreport.Handler)
	return nil
}

func (s *NoSession) getApiKeyHandler(rawcfg []byte) (apikey.Handler, error) {
	s.builderLock.RLock()
	if 0 == bytes.Compare(rawcfg, s.rawcfg) {
		h := s.apikeyHandler
		s.builderLock.RUnlock()
		return h, nil
	}
	s.builderLock.RUnlock()
	if err := s.updateHandlers(rawcfg); err != nil {
		return nil, err
	}

	// establish session
	return s.apikeyHandler, nil
}

func (s *NoSession) getQuotaHandler(rawcfg []byte) (quota.Handler, error) {
	s.builderLock.RLock()
	if 0 == bytes.Compare(rawcfg, s.rawcfg) {
		h := s.quotaHandler
		s.builderLock.RUnlock()
		return h, nil
	}
	s.builderLock.RUnlock()
	if err := s.updateHandlers(rawcfg); err != nil {
		return nil, err
	}

	// establish session
	return s.quotaHandler, nil
}

func (s *NoSession) getServicecontrolReportHandler(rawcfg []byte) (servicecontrolreport.Handler, error) {
	s.builderLock.RLock()
	if 0 == bytes.Compare(rawcfg, s.rawcfg) {
		h := s.servicecontrolreportHandler
		s.builderLock.RUnlock()
		return h, nil
	}
	s.builderLock.RUnlock()
	if err := s.updateHandlers(rawcfg); err != nil {
		return nil, err
	}

	// establish session
	return s.servicecontrolreportHandler, nil
}

func apikeyInstance(inst *apikey.InstanceMsg) *apikey.Instance {
	tmpTimestamp, err := proto.TimestampFromProto(inst.Timestamp.GetValue())
	if err != nil {
		return nil
	}
	return &apikey.Instance{
		Name: inst.Name,

		Api:          inst.Api,
		ApiVersion:   inst.ApiVersion,
		ApiOperation: inst.ApiOperation,
		ApiKey:       inst.ApiKey,
		Timestamp:    tmpTimestamp,
	}
}

func quotaInstance(inst *quota.InstanceMsg) *quota.Instance {
	return &quota.Instance{
		Name: inst.Name,

		Dimensions: decodeDimensions(inst.Dimensions),
	}
}

func servicecontrolreportInstances(in []*servicecontrolreport.InstanceMsg) []*servicecontrolreport.Instance {
	out := make([]*servicecontrolreport.Instance, 0, len(in))

	for _, inst := range in {
		tmpRequestTime, err := proto.TimestampFromProto(inst.RequestTime.GetValue())
		if err != nil {
			continue
		}
		tmpResponseTime, err := proto.TimestampFromProto(inst.ResponseTime.GetValue())
		if err != nil {
			continue
		}
		tmpResponseLatency, err := proto.DurationFromProto(inst.ResponseLatency.GetValue())
		if err != nil {
			continue
		}
		out = append(out, &servicecontrolreport.Instance{
			Name: inst.Name,

			ApiVersion:      inst.ApiVersion,
			ApiOperation:    inst.ApiOperation,
			ApiProtocol:     inst.ApiProtocol,
			ApiService:      inst.ApiService,
			ApiKey:          inst.ApiKey,
			RequestTime:     tmpRequestTime,
			RequestMethod:   inst.RequestMethod,
			RequestPath:     inst.RequestPath,
			RequestBytes:    inst.RequestBytes,
			ResponseTime:    tmpResponseTime,
			ResponseCode:    inst.ResponseCode,
			ResponseBytes:   inst.ResponseBytes,
			ResponseLatency: tmpResponseLatency,
		})
	}
	return out
}

func decodeDimensions(in map[string]*v1beta1.Value) map[string]interface{} {
	out := make(map[string]interface{}, len(in))
	for k, v := range in {
		out[k] = decodeValue(v.GetValue())
	}
	return out
}

func decodeValue(in interface{}) interface{} {
	switch t := in.(type) {
	case *v1beta1.Value_StringValue:
		return t.StringValue
	case *v1beta1.Value_Int64Value:
		return t.Int64Value
	case *v1beta1.Value_DoubleValue:
		return t.DoubleValue
	default:
		return fmt.Sprintf("%v", in)
	}
}

// HandleApiKey ...
func (s *NoSession) HandleApiKey(ctx context.Context, r *apikey.HandleApiKeyRequest) (*adptModel.CheckResult, error) {
	h, err := s.getApiKeyHandler(r.AdapterConfig.Value)
	if err != nil {
		return nil, err
	}
	inst := apikeyInstance(r.Instance)
	if inst == nil {
		return nil, fmt.Errorf("cannot transform instance")
	}
	cr, err := h.HandleApiKey(ctx, inst)
	if err != nil {
		s.env.Logger().Errorf("Could not process: %v", err)
		return nil, err
	}
	return &adptModel.CheckResult{
		Status:        cr.Status,
		ValidDuration: cr.ValidDuration,
		ValidUseCount: cr.ValidUseCount,
	}, nil
}

// HandleQuota ...
func (s *NoSession) HandleQuota(ctx context.Context, r *quota.HandleQuotaRequest) (*adptModel.QuotaResult, error) {
	h, err := s.getQuotaHandler(r.AdapterConfig.Value)
	if err != nil {
		return nil, err
	}

	qi := quotaInstance(r.Instance)
	resp := adptModel.QuotaResult{
		Quotas: make(map[string]adptModel.QuotaResult_Result),
	}
	for qt, p := range r.QuotaRequest.Quotas {
		qa := adapter.QuotaArgs{
			DeduplicationID: r.DedupId,
			QuotaAmount:     p.Amount,
			BestEffort:      p.BestEffort,
		}
		qr, err := h.HandleQuota(ctx, qi, qa)
		if err != nil {
			return nil, err
		}
		resp.Quotas[qt] = adptModel.QuotaResult_Result{
			ValidDuration: qr.ValidDuration,
			GrantedAmount: qr.Amount,
		}
	}
	if err != nil {
		s.env.Logger().Errorf("Could not process: %v", err)
		return nil, err
	}
	return &resp, nil
}

// HandleServicecontrolReport ...
func (s *NoSession) HandleServicecontrolReport(ctx context.Context, r *servicecontrolreport.HandleServicecontrolReportRequest) (*adptModel.ReportResult, error) {
	h, err := s.getServicecontrolReportHandler(r.AdapterConfig.Value)
	if err != nil {
		return nil, err
	}

	if err = h.HandleServicecontrolReport(ctx, servicecontrolreportInstances(r.Instances)); err != nil {
		s.env.Logger().Errorf("Could not process: %v", err)
		return nil, err
	}

	return &adptModel.ReportResult{}, nil
}

// Addr returns the listening address of the server
func (s *NoSession) Addr() string {
	return s.listener.Addr().String()
}

// Run starts the server run
func (s *NoSession) Run() {
	s.shutdown = make(chan error, 1)
	go func() {
		err := s.server.Serve(s.listener)

		// notify closer we're done
		s.shutdown <- err
	}()
}

// Wait waits for server to stop
func (s *NoSession) Wait() error {
	if s.shutdown == nil {
		return fmt.Errorf("server not running")
	}

	err := <-s.shutdown
	s.shutdown = nil
	return err
}

// Close gracefully shuts down the server
func (s *NoSession) Close() error {
	if s.shutdown != nil {
		s.server.GracefulStop()
		_ = s.Wait()
	}

	if s.listener != nil {
		_ = s.listener.Close()
	}

	return nil
}

// NewServicecontrolNoSessionServer creates a new no session server from given args.
func NewServicecontrolNoSessionServer(addr uint16, poolSize int) (*NoSession, error) {
	saddr := fmt.Sprintf(":%d", addr)

	gp := pool.NewGoroutinePool(poolSize, false)
	inf := servicecontrol.GetInfo()
	s := &NoSession{
		builder: inf.NewBuilder(),
		env:     handler.NewEnv(0, "servicecontrol-nosession", gp),
		rawcfg:  []byte{0xff, 0xff},
	}
	var err error
	if s.listener, err = net.Listen("tcp", saddr); err != nil {
		_ = s.Close()
		return nil, fmt.Errorf("unable to listen on socket: %v", err)
	}

	fmt.Printf("listening on :%v\n", s.listener.Addr())
	s.server = grpc.NewServer()

	apikey.RegisterHandleApiKeyServiceServer(s.server, s)
	quota.RegisterHandleQuotaServiceServer(s.server, s)
	servicecontrolreport.RegisterHandleServicecontrolReportServiceServer(s.server, s)

	return s, nil
}
